[package]
name = "actix-Web"
version = "0.1.0"
authors = ["rodrigolucianocosta <rodrigolucianocosta@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1.1.1"
